### ISSUE TITLE
can't set a cutom renderFn

### ISSUE THREAD

**Issue by alok-praks** [grindlemire/go-lucene#11]
It appears that there is no way to set custom render functions because `renderFNs` in `driver.Base` is private. So, when embedding `driver.Base` in a struct outside the `driver` package, there is no way to supply custom render functions.

**Comment by grindlemire** [comment]
Yea that was something I missed! Thanks for finding this and putting up a PR. I merged it and it is now fixed in [v0.0.9](https://github.com/grindlemire/go-lucene/releases/tag/v0.0.9).
