### ISSUE TITLE
SQL values should be single quote

### ISSUE THREAD

**Issue by hengfeiyang** [grindlemire/go-lucene#2]
Like your example:

// sqlQuery is:
```sql
SELECT *
FROM apples
WHERE
    color = red
    AND (
      NOT(type = "honey crisp")
      OR age_in_months >= 5
    )
LIMIT 10;
```

Actually, this can't work in Standard SQL mode, the value of a field must use a single quote:

```sql
SELECT *
FROM apples
WHERE
    color = red
    AND (
      NOT(type = 'honey crisp')
      OR age_in_months >= 5
    )
LIMIT 10;
```

Can I custom the symbol use single quote or double quote?

**Comment by grindlemire** [comment]
Ah yea that is a good callout, this is a bug!

**Comment by hengfeiyang** [comment]
Okay, i will create a pr for it

**Comment by grindlemire** [comment]
I also created one since it needed to be fixed in two places and needed to update the tests. Thanks for raising the issue and feel free to file other issues if you run into any!

**Comment by grindlemire** [comment]
The fix should be in v0.0.3 which I just cut.

**Comment by grindlemire** [comment]
There may be further issues with the postgres driver as I haven't run that in production yet. If you find other incompatibilities just add them to the `postgresql_test.go` test file and create an issue and I can look into it! PRs are also appreciated if you feel up for it :).

**Comment by hengfeiyang** [comment]
We are using this lib in our es proxy: https://docs.zinc.dev/docs/zplane/

But the repo hasn't make published.

Thanks for your contribute.
