### ISSUE TITLE
How to work with default fields?

### ISSUE THREAD

**Issue by gunnsth** [grindlemire/go-lucene#20]
From:
https://lucene.apache.org/core/9_4_2/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Fields

> Lucene supports fielded data. When performing a search you can either specify a field, or use the default field. The field names and default field is implementation specific.
>
> You can search any field by typing the field name followed by a colon ":" and then the term you are looking for.
>
> As an example, let's assume a Lucene index contains two fields, title and text and text is the default field. If you want to find the document entitled "The Right Way" which contains the text "don't go this way", you can enter:
> 
> title:"The Right Way" AND text:go
> or
>
> title:"The Right Way" AND go

or if the query is simply "hello world" and then we are matching some default field to that.

Any tips how to handle this case?

**Comment by grindlemire** [comment]
Hey thanks for submitting an issue!

You are right, this is a bug that I overlooked. By default it will just pass through bare literals but that is not really that useful in some cases. I just put up a PR that I'll merge which adds an option to provide a default field value if you desire. Here is an example of what you will be able to do:

```go
str, _ := lucene.Parse("a:foo AND bar", lucene.WithDefaultField("baz"))
fmt.Println(str) // prints ("a" = 'foo') AND ("baz" = 'bar')
```
Note that the query has a bare `bar` value and you call `lucene.Parse` with the new `WithDefaultField` option. The result will be that in compound expressions it will equate the `bar` to the default field you pass in (in this case `baz`).

**Comment by grindlemire** [comment]
This is now in v0.17 and I just released it now so feel free to pull the new code and give it a try!
